version: "3.8"
services:
  web:
    # container_name: web-api
    build: .
    ports:
      - "8000:80"
    networks:
      - appmanager_network
    depends_on:
      - db
  db:
    # container_name: db-sql
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "@Prog2020#"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appmanager_network
  postgres:
    image: postgres:9.6
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: AppManager
      PGDATA: /tmp
    volumes:
      - ./pgdata:/var/lib/postgresql/pg
    ports:
      - 5432:5432
    networks:
      - appmanager_network
networks:
  appmanager_network:
