name: CI API - Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: cd api/src/AppManager.Services.Api && dotnet restore
      - name: Build
        run: cd api/src/AppManager.Services.Api && dotnet build --configuration Release --no-restore
      - name: Test
        run: cd api/tests/AppManager.UnitTests && dotnet test --no-restore --verbosity normal
