name: CI Panel - Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: cd panel/ npm run build:production
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting -P production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
