name: Build and Deploy to Google Cloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# on:
#   release:
#     types: [created]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: us-east1
  DEPLOYMENT_NAME: api

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    services:
      db:
        # container_name: db-sql
        image: "mcr.microsoft.com/mssql/server"
        env:
          SA_PASSWORD: "@Prog2020#"
          ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Build the Docker image
      - name: Build
        run: |-
          cd api/ && docker build \
            --tag "gcr.io/$PROJECT_ID/$DEPLOYMENT_NAME:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          cd api/ && docker push "gcr.io/$PROJECT_ID/$DEPLOYMENT_NAME:$GITHUB_SHA"

      # Set up kustomize
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      # Deploy the Docker image to the GKE cluster
      # - name: Deploy
      #   run: |-
      #     ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
      #     ./kustomize build . | kubectl apply -f -
      #     kubectl rollout status deployment/$DEPLOYMENT_NAME
      #     kubectl get services -o wide

      - name: Deploy
        run: |-
          gcloud run deploy "$DEPLOYMENT_NAME" \
            --quiet \
            --region "$GKE_ZONE" \
            --image "gcr.io/$PROJECT_ID/$DEPLOYMENT_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
